### PR TITLE
Adds link to paketo.io when you click the header

### LINKED ISSUE #9: Add blog header
Could we add in the paketo.io header to the top of this page so it doesn't feel like a completely separate page, and provide some way to navigate back to the paketo website?
image

### PR DESCRIPTION
**Pull request by ForestEckhardt**
- Reworks the link style in order to make it line up with what is on
paketo.io and make the link on the header less intrusive.

Resolves #9 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.

### CODE REVIEW

**Review by kvedurmu — CHANGES_REQUESTED** [review]
Looks like the new CSS moved the blog title to a separate line. Could you line it up with the logo? 
image

**Comment by kvedurmu** [comment]
Hmm, I think we should think through the linking part to Paketo.io a little more because it breaks the flow of the website a little. blog.paketo.io is a separate page, and as a user I would expect that clicking on the logo on any page on the blog (including the landing page) should take me back to the main page (blog.paketo.io) in this case. We should probably have a separate button or link to paketo.io.

**Comment by ForestEckhardt** [comment]
@kvedurmu What would you expect a button/link like that to look like?

**Comment by kvedurmu** [comment]
I think something like a "Home" button on the top or bottom of the page like how [registry.buildpacks.io](https://registry.buildpacks.io/) does it could work.

**Review by kvedurmu — APPROVED** [review]

**Pull request merged**
