### PR TITLE
Add new post

### PR DESCRIPTION
**Pull request by davidmirror-ops**
Signed-off-by: David Espejo <daespejo@vmware.com>

## Summary
Add blog post outlining the findings from the OSS Health Assessment as presented during May 24 [Working Group meeting 
](https://www.youtube.com/watch?v=3Y7szy0TbDI)

Post date is in the future accounting for possible reviews/fixes that could last a week

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
@davidmirror-ops I will take a closer look at this hopefully soon. In the meantime could you add a picture to the `assets/images/authors` directory and could you add your name to the under the `[params.authors]` section in the `config.toml` in the root of the project. That should get your profile ready to be displayed!

**Comment by davidmirror-ops** [comment]
The goal is to provide a public resource that summarizes the actions we will be taking to open more communication paths, improve tools and/or procedures and in general, keep working in ways to enable the Paketo community to collaborate even better. 

The action plan could be a Github project but the blog post allows me to provide more context. 

In summary, the goal is to make the action plan completely traceable and open so everyone can give their opinions, contribute and/or easily know what's the current status.

**Comment by ForestEckhardt** [comment]
I think I would appreciate if you could lay that purpose out in the blog itself otherwise I am not sure why I would want to funnel to this blog.

**Comment by davidmirror-ops** [comment]
I put it in the third paragraph. The ideal location for the goals would be at the beginning but if that's the expectation, I'll have to rephrase most of the post to make sure there's enough context

**Comment by ForestEckhardt** [comment]
> I put it in the third paragraph. The ideal location for the goals would be at the beginning but if that's the expectation, I'll have to rephrase most of the post to make sure there's enough context

I am confused. Are you planning on drastically reworking this or is that rework contingent on whether or not the motivation has become clearer in my eyes?

**Comment by ForestEckhardt** [comment]
@davidmirror-ops Is this blog ready for consideration? I am a little confused on the status.

**Comment by davidmirror-ops** [comment]
@ForestEckhardt yes, changed words and paragraphs hoping it's more clear

**Comment by ForestEckhardt** [comment]
@paketo-buildpacks/content-maintainers Could I get one more set of eyes to take a look at this?

**Review by TisVictress — APPROVED** [review]

**Review by ForestEckhardt — APPROVED** [review]

**Pull request merged**
